### ISSUE TITLE
Connection Refused for DynamoDB

### ISSUE THREAD

**Issue by sanhardik** [cnadiminti/docker-dynamodb-local#3]
Hello, 
I am trying to create a docker container to run local python tests. 
The code is used to test functionality that depends on MYSQL, Redis and DynamoDB
This is my docker-compose file. 

```
version: '3'
services:
  app:
    build: .
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=foo
      - DATABASE_PASSWORD=bar
      - CACHE_HOST=cache
      - BUGSNAG_API_KEY=key
      - DYNAMODB_URL='http://localhost:8000/'
    depends_on:
      - database
      - cache
      - dynamoDB
  database:
    image: "mariadb:10.0.24"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=bar
      - MYSQL_ROOT_PASSWORD=bar
  cache:
    image: "redis:3.2"
  dynamoDB:
    image: cnadiminti/dynamodb-local:latest
    command: -inMemory
    ports:
      - '8000:8000'
```
I am keeping on Getting Connection refused with the following error message 
`DEBUG:botocore.auth:CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.0
host:localhost:8000
x-amz-date:20171023T005945Z
x-amz-target:DynamoDB_20120810.CreateTable

content-type;host;x-amz-date;x-amz-target
09548050458cafc204a942a4de3da965dcadfa2e320004b6727fc7f8cb86cb93
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20171023T005945Z
20171023/ap-southeast-2/dynamodb/aws4_request
679032bcc6577cddc2eceb7175969a905fd94b15220fe83eb3da2c24839938c7
DEBUG:botocore.auth:Signature:
aa01cbb5a15840e8dae2ba425b065f60f48db5251919641ff03510f52a5467b8
DEBUG:botocore.endpoint:Sending http request: <PreparedRequest [POST]>
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:botocore.endpoint:ConnectionError received when sending HTTP request.
`
